#!/usr/bin/env python
"""Regenerate requirements.lock and requirements-dev.lock with pip-tools.

    python tools/make_lock.py

requirements.lock pins every runtime package, transitively, from requirements.txt;
requirements-dev.lock adds the development tools from requirements-dev.txt, constrained to the
same runtime versions. Both resolve against PyPI for Python 3.11.

PyTorch is the one package that comes from a different index per station type: CI and CPU
stations install the CPU build from https://download.pytorch.org/whl/cpu and GPU stations the
CUDA build (README.md). PyPI's Linux wheel of torch depends on NVIDIA CUDA packages that the CPU
build does not need and the CUDA build brings with it, so those lines are left out of the lock;
the torch version itself is pinned, and "torch==X" is satisfied by both "X+cpu" and "X+cuNNN".
Hashes are not recorded for the same reason: pip's hash mode would need one hash set per index.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GPU_ONLY = re.compile(r"^(nvidia-|cuda-|triton==)")
HEADER = (
    "# Generated by tools/make_lock.py; do not edit by hand. Exact transitive pins for Python 3.11.\n"
    "# NVIDIA CUDA packages and triton are left out on purpose: see tools/make_lock.py.\n"
)


def compile_lock(inputs: list[Path], output: Path, constraints: Path | None = None) -> None:
    pip_compile = shutil.which("pip-compile")
    if not pip_compile:
        raise SystemExit("pip-compile not found: pip install -r requirements-dev.txt first")
    cmd = [
        pip_compile,
        "--quiet",
        "--strip-extras",
        "--no-header",
        "--no-annotate",
        "--output-file",
        str(output),
    ]
    if constraints:
        cmd += ["--constraint", str(constraints)]
    cmd += [str(p) for p in inputs]
    subprocess.run(cmd, check=True, cwd=ROOT)
    lines = [ln for ln in output.read_text(encoding="utf-8").splitlines() if ln.strip() and not GPU_ONLY.match(ln)]
    output.write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    runtime = ROOT / "requirements.lock"
    compile_lock([ROOT / "requirements.txt"], runtime)
    compile_lock([ROOT / "requirements.txt", ROOT / "requirements-dev.txt"], ROOT / "requirements-dev.lock", runtime)
    print("wrote requirements.lock and requirements-dev.lock")


if __name__ == "__main__":
    main()
