#!/usr/bin/env python
"""Regenerate the hashed lock files with pip-tools, or check that they are current.

    python tools/make_lock.py            # rewrite every lock file
    python tools/make_lock.py --check    # exit 1 and print the difference when a lock file is out of date
    python tools/make_lock.py --pypi-only   # only the PyPI lock files, where download.pytorch.org is unreachable

Every lock file lists the sha256 hash of each file pip may install, for Python 3.11 on Windows and Linux, so pip
refuses a download that differs from what was reviewed (Engineering standard, "Code style"; stage S04):

    requirements.lock             runtime packages from PyPI, except PyTorch
    requirements-dev.lock         the same versions plus the development and CI tools
    requirements-build.lock       the same versions plus PyInstaller, for the Windows build (ADR 0007)
    requirements-torch-cpu.lock   PyTorch's CPU build, from download.pytorch.org/whl/cpu (CI, CPU stations)
    requirements-torch-cuda.lock  PyTorch's CUDA build, from download.pytorch.org/whl/cu130, and on Linux the NVIDIA
                                  libraries it needs (GPU stations)

Install PyTorch first, without dependencies, then the rest, then let pip confirm nothing is missing:

    python -m pip install --require-hashes --no-deps -r requirements-torch-cpu.lock
    python -m pip install --require-hashes -r requirements.lock      (developers and CI: requirements-dev.lock)
    python -m pip check

PyTorch has lock files of its own because one version is three different sets of files: PyPI's (whose Linux wheel
pulls in gigabytes of NVIDIA packages), the CPU index's (2.14.1+cpu) and the CUDA index's (2.14.1+cu130). Hash mode
checks files, so each station type needs the hashes of its own build. torch's other dependencies (filelock, sympy,
setuptools and so on) are the same on every index and stay in requirements.lock, hashed from PyPI.

pip-compile drops a requirement whose platform marker is false where it runs, so a Windows-only requirement such as
`colorama ; sys_platform == "win32"` in requirements-dev.txt (pytest, bandit and build need it on Windows) or
PyInstaller's `pefile` in requirements-build.txt is resolved on its own and added with its marker. The output is the
same whichever platform runs this tool, and the --check job in CI fails when a lock file no longer matches its inputs.

pip-compile resolves the versions; the hashes come from the index itself (the sha256 that PyPI and PyTorch's index
publish for every file of the pinned version, on every platform), because pip-compile --generate-hashes downloads
every wheel to hash it, which for PyTorch's CUDA build is tens of gigabytes.
"""

from __future__ import annotations

import argparse
import difflib
import html
import json
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from functools import cache
from pathlib import Path

from packaging.utils import InvalidSdistFilename, InvalidWheelFilename, parse_sdist_filename, parse_wheel_filename
from packaging.version import Version

ROOT = Path(__file__).resolve().parents[1]
PYPI = "https://pypi.org/simple"
TORCH_BUILDS = {  # lock file suffix: (index, local version label)
    "cpu": ("https://download.pytorch.org/whl/cpu", "cpu"),
    "cuda": ("https://download.pytorch.org/whl/cu130", "cu130"),
}
GPU_ONLY = re.compile(r"^(nvidia-|cuda-|triton$)")
LINUX = 'platform_system == "Linux"'
CONTINUATION = "\\"
INSTALL = (
    "# Install: python -m pip install --require-hashes --no-deps -r requirements-torch-cpu.lock (GPU station: -cuda),\n"
    "#   then python -m pip install --require-hashes -r {lock}, then python -m pip check (tools/make_lock.py).\n"
)
HEADERS = {
    "requirements.lock": "# Runtime packages for Python 3.11 on Windows and Linux, except PyTorch.\n"
    + INSTALL.format(lock="requirements.lock"),
    "requirements-dev.lock": "# Runtime packages plus the development and CI tools, except PyTorch.\n"
    + INSTALL.format(lock="requirements-dev.lock"),
    "requirements-build.lock": "# Runtime packages plus PyInstaller for the Windows build (ADR 0007), except PyTorch.\n"
    + INSTALL.format(lock="requirements-build.lock"),
    "requirements-torch-cpu.lock": "# PyTorch's CPU build for CI and CPU stations; install it first.\n",
    "requirements-torch-cuda.lock": "# PyTorch's CUDA build for GPU stations; install it first.\n",
}
GENERATED = "# Generated by tools/make_lock.py with hashes; do not edit by hand.\n"


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def blocks(text: str) -> list[tuple[str, str]]:
    """Split pip-compile output into (package name, its lines), dropping comments and index options."""
    out: list[tuple[str, str]] = []
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[0].isspace():
            name, body = out[-1]
            out[-1] = (name, f"{body}\n{line}")
        elif not line.startswith("-"):
            m = re.match(r"[A-Za-z0-9][A-Za-z0-9._-]*", line)
            if not m:
                raise SystemExit(f"cannot read pip-compile line: {line}")
            out.append((norm(m.group(0)), line))
    return out


def with_marker(block: str, marker: str) -> str:
    first, sep, rest = block.partition("\n")
    cont = " " + CONTINUATION if sep else ""
    return f"{first.rstrip(' ' + CONTINUATION)} ; {marker}{cont}{sep}{rest}"


def pins(text: str) -> str:
    """The name==version lines of a lock, without hashes or markers, for use as constraints."""
    lines = (body.split("\n", 1)[0].split(";", 1)[0].rstrip(" \\") for _, body in blocks(text))
    return "\n".join(lines) + "\n"


def marked(path: Path) -> list[tuple[str, str]]:
    """The requirements in an input file that carry a platform marker, as (requirement, marker)."""
    out = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if ";" in line:
            req, marker = line.split(";", 1)
            out.append((req.strip(), marker.strip()))
    return out


def compile_text(
    inputs: list[str],
    tmp: Path,
    *,
    index: str = PYPI,
    extra: tuple[str, ...] = (),
    constraints: str | None = None,
    previous: Path | None = None,
) -> str:
    """Run pip-compile and hash its pins; the previous lock, when given, keeps every pin that still fits."""
    pip_compile = shutil.which("pip-compile")
    if not pip_compile:
        raise SystemExit("pip-compile not found: python -m pip install --require-hashes -r requirements-dev.lock first")
    work = Path(tempfile.mkdtemp(dir=tmp))
    req = work / "in.txt"
    req.write_text("\n".join(inputs) + "\n", encoding="utf-8")
    out = work / "out.txt"
    if previous is not None and previous.exists():
        shutil.copyfile(previous, out)
    cmd = [pip_compile, "--quiet", "--allow-unsafe", "--strip-extras", "--no-header"]
    cmd += ["--no-annotate", "--no-emit-index-url", "--index-url", index, "--output-file", str(out)]
    for url in extra:
        cmd += ["--extra-index-url", url]
    if constraints is not None:
        (work / "constraints.txt").write_text(constraints, encoding="utf-8")
        cmd += ["--constraint", str(work / "constraints.txt")]
    subprocess.run([*cmd, str(req)], check=True, cwd=ROOT)
    return "\n".join(hashed(body, (index, *extra)) for _, body in blocks(out.read_text(encoding="utf-8"))) + "\n"


@cache
def index_files(index: str, name: str) -> tuple[tuple[str, str], ...]:
    """(file name, sha256) of every file the index lists for a project (PEP 691 JSON, or the HTML simple page)."""
    accept = "application/vnd.pypi.simple.v1+json, text/html;q=0.1"
    request = urllib.request.Request(f"{index}/{norm(name)}/", headers={"Accept": accept})
    try:
        with urllib.request.urlopen(request, timeout=120) as response:  # noqa: S310 (https index URLs above)
            body = response.read().decode("utf-8")
            kind = response.headers.get_content_type()
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return ()
        raise
    if kind.endswith("json"):
        files = json.loads(body)["files"]
        return tuple((f["filename"], f["hashes"]["sha256"]) for f in files if "sha256" in f["hashes"])
    links = re.findall(r'<a [^>]*href="[^"#]*#sha256=([0-9a-f]{64})"[^>]*>([^<]+)</a>', body)
    return tuple((html.unescape(fn).strip(), digest) for digest, fn in links)


def file_version(filename: str) -> Version | None:
    try:
        if filename.endswith(".whl"):
            return parse_wheel_filename(filename)[1]
        return parse_sdist_filename(filename)[1]
    except (InvalidWheelFilename, InvalidSdistFilename):
        return None


def hashed(block: str, indexes: tuple[str, ...]) -> str:
    """A pin with the sha256 of every file of that version on the given indexes, for every platform."""
    pin = block.split("\n", 1)[0].rstrip(" " + CONTINUATION)
    name, version = pin.split("==", 1)
    digests = sorted(
        {digest for index in indexes for fn, digest in index_files(index, name) if file_version(fn) == Version(version)}
    )
    if not digests:
        raise SystemExit(f"no published sha256 for {pin} on {', '.join(indexes)}")
    return f"{pin} {CONTINUATION}\n" + f" {CONTINUATION}\n".join(f"    --hash=sha256:{d}" for d in digests)


def requirement_lines(path: Path) -> list[str]:
    lines = (raw.split("#", 1)[0].strip() for raw in path.read_text(encoding="utf-8").splitlines())
    return [line for line in lines if line and ";" not in line]


def pypi_lock(name: str, inputs: list[Path], tmp: Path, constraints: str | None, target: Path) -> str:
    reqs = [line for path in inputs for line in requirement_lines(path)]
    special = [m for path in inputs for m in marked(path)]
    skip = {norm(re.split(r"[=<>!~ ]", req, maxsplit=1)[0]) for req, _ in special} | {"torch"}
    text = compile_text(reqs, tmp, constraints=constraints, previous=target / name)
    kept = [body for pkg, body in blocks(text) if pkg not in skip and not GPU_ONLY.match(pkg)]
    for req, marker in special:
        kept += [with_marker(body, marker) for _, body in blocks(compile_text([req], tmp, constraints=constraints))]
    return GENERATED + HEADERS[name] + "\n".join(kept) + "\n"


def torch_lock(build: str, version: str, shared: str, tmp: Path, target: Path) -> str:
    index, label = TORCH_BUILDS[build]
    name = f"requirements-torch-{build}.lock"
    text = compile_text(
        [f"torch=={version}+{label}"],
        tmp,
        index=index,
        extra=(PYPI,),
        constraints=pins(shared),
        previous=target / name,
    )
    in_shared = {pkg for pkg, _ in blocks(shared)}
    kept = [body if pkg == "torch" else with_marker(body, LINUX) for pkg, body in blocks(text) if pkg not in in_shared]
    options = f"--index-url {index}\n" + (f"--extra-index-url {PYPI}\n" if build == "cuda" else "")
    return GENERATED + HEADERS[name] + options + "\n".join(kept) + "\n"


def build_all(tmp: Path, target: Path = ROOT, *, torch_builds: bool = True) -> dict[str, str]:
    runtime = pypi_lock("requirements.lock", [ROOT / "requirements.txt"], tmp, None, target)
    dev_inputs = [ROOT / "requirements.txt", ROOT / "requirements-dev.txt"]
    texts = {"requirements.lock": runtime}
    texts["requirements-dev.lock"] = pypi_lock("requirements-dev.lock", dev_inputs, tmp, pins(runtime), target)
    build_inputs = [ROOT / "requirements.txt", ROOT / "requirements-build.txt"]
    texts["requirements-build.lock"] = pypi_lock("requirements-build.lock", build_inputs, tmp, pins(runtime), target)
    torch = next(line for line in requirement_lines(ROOT / "requirements.txt") if line.startswith("torch=="))
    version = torch.split("==", 1)[1].strip()
    for build in TORCH_BUILDS if torch_builds else ():
        texts[f"requirements-torch-{build}.lock"] = torch_lock(build, version, runtime, tmp, target)
    return texts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--check", action="store_true", help="compare with the committed lock files instead of writing")
    ap.add_argument("--pypi-only", action="store_true", help="leave the PyTorch lock files out (no PyTorch index)")
    args = ap.parse_args()
    with tempfile.TemporaryDirectory() as tmp:
        texts = build_all(Path(tmp), torch_builds=not args.pypi_only)
    if not args.check:
        for name, text in texts.items():
            (ROOT / name).write_text(text, encoding="utf-8", newline="\n")
        print("wrote " + ", ".join(texts))
        return 0
    stale = []
    for name, text in texts.items():
        path = ROOT / name
        now = path.read_text(encoding="utf-8") if path.exists() else ""
        if now != text:
            stale.append(name)
            sys.stdout.writelines(difflib.unified_diff(now.splitlines(True), text.splitlines(True), name, name))
            print(f"----- {name} as tools/make_lock.py writes it -----\n{text}----- end of {name} -----")
    if stale:
        print(f"Out of date: {', '.join(stale)}. Run python tools/make_lock.py and commit the result.")
        return 1
    print(f"All {len(texts)} lock files match their inputs.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
